nav_trade_tracker:
    resource: "@NavTradeTrackerBundle/Controller/"
    type:     annotation
    prefix:   /nav

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cron:
    resource: '@AppBundle/Resources/config/routing.yml'