# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    tradetracker.klantid: 137293
    tradetracker.sleutel: 01856d1ef05f685bfe2a82c3412aa27212d6e8cf
    tradetracker.locale: nl_NL

services:
    tradetracker:
        class: AppBundle\Client\TradeTrackerClient
        arguments: ['%tradetracker.klantid%', '%tradetracker.sleutel%', '@service_container']