<?php

namespace Nav\TradeTrackerBundle\Repository;

/**
 * CampaignNewsItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignNewsItemRepository extends \Doctrine\ORM\EntityRepository
{
}
